services:
  spark-master:
    image: jupyter/pyspark-notebook:latest
    container_name: spark-master
    command: >
      start.sh bash -c "/opt/spark/sbin/start-master.sh && tail -f /dev/null"
    ports:
      - "7077:7077"
      - "8080:8080"
    environment:
      - SPARK_MASTER_HOST=spark-master
    networks:
      - spark-network
    volumes:
      - ./data:/home/jovyan/data
      - ./notebooks:/home/jovyan/work

  spark-worker:
    image: jupyter/pyspark-notebook:latest
    depends_on:
      - spark-master
    command: >
      bash -c "/opt/spark/sbin/start-worker.sh spark://spark-master:7077 && tail -f /dev/null"
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2G
    ports: []
    networks:
      - spark-network
    volumes:
      - ./data:/home/jovyan/data
      - ./notebooks:/home/jovyan/work

  jupyter:
    image: jupyter/pyspark-notebook:latest
    depends_on:
      - spark-master
    ports:
      - "8888:8888" # Jupyter Notebook 접속 포트
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN= # 빈 값이면 토큰 없이 접속 (보안 유의)
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/data
      - ./dataset:/home/jovyan/dataset
      - ./weather.csv:/home/jovyan/weather.csv
      - ./W4M2.ipynb:/home/jovyan/W4M2.ipynb
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge
